name: Push a release to Maven Central

on:
    push:
        tags:
            - '4.*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
        steps:
            - name: Git checkout
              uses: actions/checkout@v4
            - name: Java setup
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
            - name: Install just
              uses: taiki-e/install-action@just
            - name: Deploy to Maven Central
              run: just deploy-to-maven-central
